FROM debian:stable
MAINTAINER Anh K. Huynh "kyanh@theslinux.org"
ENV DEBIAN_FRONTEND noninteractive

VOLUME /life
VOLUME /wife
VOLUME /children
VOLUME /boss
VOLUME /salary
VOLUME /next-generation-facebook
VOLUME /next-generation-google
VOLUME /c100k-problem-aka-nginx2
VOLUME /next-mobile-platform
VOLUME /next-generation-shit

EXPOSE 80

RUN echo Docker makes life easier.
RUN echo Everything can be put in a container.
RUN echo Let us do it. Put every shit in a shit.

CMD ["/bin/fail"]
