FROM debian:stable
MAINTAINER Anh K. Huynh "kyanh@theslinux.org"
ENV DEBIAN_FRONTEND noninteractive

VOLUME /life
VOLUME /wife
VOLUME /children
VOLUME /boss
VOLUME /salary
VOLUME /next-generation-facebook
VOLUME /next-generation-google
VOLUME /c100k-problem-aka-nginx2
VOLUME /next-mobile-platform
VOLUME /next-generation-shit

EXPOSE 80

CMD ["/bin/fail"]
