#!/bin/bash

if [[ -z "${SUPERVISOR_PASSWD}" ]]; then
  _PASSWORD="$RANDOM.$RANDOM"
  echo >&2 ":: Supervisor web console: admin's password is $_PASSWORD"
else
  _PASSWORD="${SUPERVISOR_PASSWD}"
fi

_LOG_LEVEL="${SUPERVISOR_LOG_LEVEL:-info}"

cat \
  > /etc/supervisord.conf \
<<EOF
;
; supervisord main config file - v0.1
; Do not edit this file
;

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                      ; sockef file mode (default 0700)

[inet_http_server]
port=127.0.0.1:9001
username=admin
password=${_PASSWORD}

[supervisord]
nodaemon=true
logfile=/supervisor/__daemon.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/supervisor/         ; ('AUTO' child log dir, default $TEMP)
logfile_maxbytes=50MB            ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10               ; (num of main logfile rotation backups;default 10)
loglevel=$SUPERVISOR_LOG_LEVEL   ; (log level;default info; others: debug,warn,trace)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[include]
files = /etc/s.supervisor/*.s
EOF

exec /usr/bin/supervisord --configuration /etc/supervisord.conf
